# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

# on main and tags
on: push

jobs:
  build-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.build-release.outputs.upload_url }}

    steps:
      - name: Create release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        id: build-release
        uses: shogo82148/actions-create-release@v1

  build:

    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.build-release.outputs.upload_url }}
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6.1

    - name: Build with Gradle
      run: gradle build


    - name: Upload artifact
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.build-release.outputs.upload_url }}
